# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
orbs:
  python: dialogue/python@1.1.0
jobs:
  build-python-3.6:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install
            pip install pytest

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest

  publish:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: create packages and upload to test pypi
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade setuptools wheel twine
            python setup.py sdist
            python setup.py bdist_wheel
            twine upload --repository-url https://test.pypi.org/legacy/ dist/*

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build-python-3.6:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - publish:
          requires:
            - build-python-3.6
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/